% Axis Tick test

%%
clr,
x=[-2*pi():.1:2*pi()];
ax1=axes;
ax2=axes;

figure(1)
plot(x,sin(x),'parent',ax1)

set(ax1,...
 'xlim',[-2*pi() 2*pi()],...
 'xtick',[],...
 'xticklabel',{},...
 'ylim',[-1 1],...
 'ytick',[-1:.5:1],...
 'yticklabel',{'-a' '-a/2' '0' 'a/2' 'a'},...
 'fontsize',20)

ylabel(ax1,'a\cdotsin(\phi)',...
 'fontname','helvetica',...
 'fontsize',30)

set(ax2,...
 'xlim',[-2*pi() 2*pi()],...
 'xtick',[-2*pi():pi()/2:2*pi()],...
 'xticklabel',{'-2p' '-3p/2' '-p' '-p/2' '0' 'p/2' 'p' '3p/2' '2p'},...
 'ylim',[-1 1],...
 'ytick',[],...
 'yticklabel',{},...
 'fontname','symbol',...
 'fontsize',20,...
 'position',get(ax1,'position'),...
 'color','none')

xlabel(ax2,'angle \phi from -2\pi to 2\pi',...
 'fontname','helvetica')

grid on
figure(gcf)




%%
clr,

x=[-2*pi():.1:2*pi()];

figure(2)
plot(x,pi*sin(x))

set(gca,...
 'xlim',[-2*pi() 2*pi()],...
 'xtick',[-2*pi():pi()/2:2*pi()],...
 'xticklabel',{'-2p' '-3p/2' '-p' '-p/2' '0' 'p/2' 'p' '3p/2' '2p'},...
 'ylim',[-pi() pi()],...
 'ytick',[-pi():pi()/2:pi()],...
 'yticklabel',{'-p' '-p/2' '0' 'p/2' 'p'},...
 'fontname','symbol',...
 'fontsize',20)


grid on
figure(gcf)
